-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1k9/UtdqW36nRyTE
5UKILZYmQyqUlP4sI8xhExbYIUmgCgYIKoZIzj0DAQehRANCAARVIcGbLaE0sxl0
M+4+yNKcOHY3J/9gz/zFBxfwM35MGX+j7mUKcTYBjU4dyPDf/ssTBuamUeWniZA+
vBSrYWH8
-----END PRIVATE KEY-----